### ISSUE TITLE
Click on submit bottom not erro reporter

### ISSUE THREAD

**Issue by ribsousa** [CheerfulLab/frontSpelling-plugin#3]
By clicking the submit button the error is not reported, check the backend and there are no reported error

debug return: 

`POST /backend/cheerfullab/frontendspelling/spellingrequests/create_ajax 404 (Not Found)`

**Comment by haegemon** [comment]
Hello
That seems like broken routing at web server. Can you dump webserver (nginx or apache or etc) site confug?

**Comment by ribsousa** [comment]
All plugins works fine!, broken routing?

**Comment by haegemon** [comment]
It`s assumption. 
404 - show either backend doesn`t get request ( if it gets it return 200 or 401) or backend get request but not found controller or action or module
I assume that if you post your server config it help fix bug.
What is your operation system at server, what kind of web server you use?

**Comment by ribsousa** [comment]
Linux and apache

**Comment by haegemon** [comment]
I can`t reproduce your bug. I try with apache2 apd apache.
I need more data about your server configuration. Can you post logs of your server with 404 request and domain config, with changed domain name?

**Comment by haegemon** [comment]
Can't reproduce
